"""Add views table

Revision ID: add_views_table
Revises: bdc0e1c30c77
Create Date: 2025-01-27 12:00:00.000000

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add_views_table"
down_revision: Union[str, None] = "bdc0e1c30c77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "views",
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.String(length=255), nullable=False),
        sa.Column("viewed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.feed_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("feed_id", "account_id"),
    )
    op.create_index(
        "idx_views_feed_account",
        "views",
        ["feed_id", "account_id"],
        unique=False,
    )
    op.create_index(op.f("ix_views_account_id"), "views", ["account_id"], unique=False)
    op.create_index(op.f("ix_views_feed_id"), "views", ["feed_id"], unique=False)
    op.create_index(op.f("ix_views_viewed_at"), "views", ["viewed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_views_viewed_at"), table_name="views")
    op.drop_index(op.f("ix_views_feed_id"), table_name="views")
    op.drop_index(op.f("ix_views_account_id"), table_name="views")
    op.drop_index("idx_views_feed_account", table_name="views")
    op.drop_table("views")
    # ### end Alembic commands ###
