"""Init database

Revision ID: bdc0e1c30c77
Revises:
Create Date: 2025-11-29 18:36:42.587223

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bdc0e1c30c77"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feeds",
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.String(length=255), nullable=False),
        sa.Column("has_followed", sa.Boolean(), nullable=False),
        sa.Column("has_liked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("feed_id"),
    )
    op.create_index(op.f("ix_feeds_account_id"), "feeds", ["account_id"], unique=False)
    op.create_index(op.f("ix_feeds_created_at"), "feeds", ["created_at"], unique=False)
    op.create_table(
        "followers",
        sa.Column("follower", sa.String(length=255), nullable=False),
        sa.Column("follow_for", sa.String(length=255), nullable=False),
        sa.Column("followed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("follower", "follow_for"),
    )
    op.create_index(
        "idx_followers_composite",
        "followers",
        ["follower", "follow_for"],
        unique=False,
    )
    op.create_index(
        "idx_followers_follow_for",
        "followers",
        ["follow_for"],
        unique=False,
    )
    op.create_index("idx_followers_follower", "followers", ["follower"], unique=False)
    op.create_index(
        op.f("ix_followers_follow_for"),
        "followers",
        ["follow_for"],
        unique=False,
    )
    op.create_index(
        op.f("ix_followers_followed_at"),
        "followers",
        ["followed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_followers_follower"),
        "followers",
        ["follower"],
        unique=False,
    )
    op.create_table(
        "images",
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("feed_id", sa.UUID(), nullable=True),
        sa.Column("uploader", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("blurhash", sa.String(length=255), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.feed_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("image_id"),
    )
    op.create_index(op.f("ix_images_feed_id"), "images", ["feed_id"], unique=False)
    op.create_index(
        op.f("ix_images_uploaded_at"),
        "images",
        ["uploaded_at"],
        unique=False,
    )
    op.create_index(op.f("ix_images_uploader"), "images", ["uploader"], unique=False)
    op.create_table(
        "likes",
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.String(length=255), nullable=False),
        sa.Column("liked_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.feed_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("feed_id", "account_id"),
    )
    op.create_index(
        "idx_likes_feed_account",
        "likes",
        ["feed_id", "account_id"],
        unique=False,
    )
    op.create_index(op.f("ix_likes_account_id"), "likes", ["account_id"], unique=False)
    op.create_index(op.f("ix_likes_feed_id"), "likes", ["feed_id"], unique=False)
    op.create_index(op.f("ix_likes_liked_at"), "likes", ["liked_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_likes_liked_at"), table_name="likes")
    op.drop_index(op.f("ix_likes_feed_id"), table_name="likes")
    op.drop_index(op.f("ix_likes_account_id"), table_name="likes")
    op.drop_index("idx_likes_feed_account", table_name="likes")
    op.drop_table("likes")
    op.drop_index(op.f("ix_images_uploader"), table_name="images")
    op.drop_index(op.f("ix_images_uploaded_at"), table_name="images")
    op.drop_index(op.f("ix_images_feed_id"), table_name="images")
    op.drop_table("images")
    op.drop_index(op.f("ix_followers_follower"), table_name="followers")
    op.drop_index(op.f("ix_followers_followed_at"), table_name="followers")
    op.drop_index(op.f("ix_followers_follow_for"), table_name="followers")
    op.drop_index("idx_followers_follower", table_name="followers")
    op.drop_index("idx_followers_follow_for", table_name="followers")
    op.drop_index("idx_followers_composite", table_name="followers")
    op.drop_table("followers")
    op.drop_index(op.f("ix_feeds_created_at"), table_name="feeds")
    op.drop_index(op.f("ix_feeds_account_id"), table_name="feeds")
    op.drop_table("feeds")
    # ### end Alembic commands ###
